version: '3.8'

services:
    utcourt-botfront:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: utcourt-botfront
        ports:
            - 8080:8080
        command:
            - run
            - prod
