version: "3.3"
services:
  botfront:
    build:
      context: .
      dockerfile: Dockerfile
    image: botfront:latest
    container_name: botfront
    ports:
      - 9080:9080
    command:
      - npm
      - run 
      - prod
