version: '3.8'

services:
    botfront:
        build:
            context: .
            dockerfile: Dockerfile_local
        image: sivasirius/utcourt-botfront:latest
        container_name: botfront
        ports:
            - 9080:9080
        command:
            - npm
            - run
            - test
