version: '3.8'

services:
    botfront:
        build:
            context: .
            dockerfile: Dockerfile
        image: utcourtchatbotregistry.azurecr.io/utcourt-botfront:latest
        container_name: botfront
        ports:
            - 9080:9080
