import ConnectedWidget from './src';
import {
    addUserMessage,
    addResponseMessage,
    addCarousel,
    addCustomCarousel,
    addCustomCard,
    addVideoSnippet,
    addImageSnippet,
    addButtons,
    renderCustomComponent,
    isOpen,
    isVisible,
    openChat,
    closeChat,
    toggleChat,
    showChat,
    hideChat,
    toggleFullScreen,
    toggleMessageTone,
    toggleInputDisabled,
    dropMessages,
    send,
} from './src/store/actions/dispatcher';

export {
    ConnectedWidget as Widget,
    addUserMessage,
    addResponseMessage,
    addCarousel,
    addCustomCarousel,
    addCustomCard,
    addVideoSnippet,
    addImageSnippet,
    addButtons,
    renderCustomComponent,
    isOpen,
    isVisible,
    openChat,
    closeChat,
    toggleChat,
    showChat,
    hideChat,
    toggleFullScreen,
    toggleMessageTone,
    toggleInputDisabled,
    dropMessages,
    send,
};
