version: '3.8'

services:
    botfront:
        build:
            context: .
            dockerfile: Dockerfile
        image: test-slc-nexus-nxrm01.utahcourts.local/botfront:dev-latest
        container_name: botfront
        ports:
            - 80:80
